# Generated by Django 5.2.4 on 2025-08-11 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材一覧',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='記録日')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '学習中'), ('done', '完了')], max_length=20, verbose_name='学習ステータス')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '進捗',
                'verbose_name_plural': '進捗一覧',
            },
        ),
        migrations.CreateModel(
            name='MaterialNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('order', models.PositiveBigIntegerField(default=0, verbose_name='表示順')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_nodes', to='learning_content.material')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='learning_content.materialnode')),
            ],
            options={
                'verbose_name': '教材学習項目',
                'verbose_name_plural': '教材学習項目一覧',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'order'), name='unique_order_per_parent')],
            },
        ),
    ]
