# Generated by Django 5.2.4 on 2025-07-28 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材一覧',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='レッスンタイトル')),
                ('order', models.IntegerField(verbose_name='表示順序')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_content', to='learning_content.material', verbose_name='教材')),
            ],
            options={
                'verbose_name': 'レッスン',
                'verbose_name_plural': 'レッスン一覧',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='記録日')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '学習中'), ('done', '完了')], max_length=20, verbose_name='学習ステータス')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='learning_content.lesson', verbose_name='レッスン')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '進捗',
                'verbose_name_plural': '進捗一覧',
            },
        ),
    ]
