# Generated by Django 5.2.4 on 2025-08-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('order', models.PositiveBigIntegerField(default=0, verbose_name='表示順')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_nodes', to='learning_content.material')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning_content.materialnode')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'order'), name='unique_order_per_parent')],
            },
        ),
    ]
