# Generated by Django 5.2.4 on 2025-08-12 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='material_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='learning_content.materialnode', verbose_name='教材学習項目'),
        ),
    ]
