# Generated by Django 5.2.4 on 2025-08-13 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_content', '0002_progress_material_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['title'], 'verbose_name': '教材', 'verbose_name_plural': '教材一覧'},
        ),
        migrations.AlterModelOptions(
            name='materialnode',
            options={'ordering': ['material', 'order'], 'verbose_name': '教材学習項目', 'verbose_name_plural': '教材学習項目一覧'},
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_materials', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
        migrations.AddField(
            model_name='material',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='materialnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='materialnode',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_material_nodes', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
        migrations.AddField(
            model_name='materialnode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialnode',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='materialnode',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='learning_content.material'),
        ),
        migrations.AlterField(
            model_name='materialnode',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning_content.materialnode'),
        ),
        migrations.AlterField(
            model_name='materialnode',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='記録日'),
        ),
    ]
