# Generated by Django 5.2.4 on 2025-08-14 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_content', '0003_alter_material_options_alter_materialnode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_materials', to='learning_content.material', verbose_name='元テンプレート'),
        ),
    ]
