# Generated by Django 5.2.4 on 2025-07-27 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'レッスン', 'verbose_name_plural': 'レッスン一覧'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '教材', 'verbose_name_plural': '教材一覧'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': '進捗', 'verbose_name_plural': '進捗一覧'},
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.material', verbose_name='教材'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(verbose_name='表示順序'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, verbose_name='レッスンタイトル'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='記録日'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='lessons.lesson', verbose_name='レッスン'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('not_started', '未開始'), ('in_progress', '学習中'), ('done', '完了')], max_length=20, verbose_name='学習ステータス'),
        ),
    ]
