# Generated by Django 5.2.4 on 2025-08-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_materialnode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialnode',
            options={'ordering': ['order'], 'verbose_name': '教材学習項目', 'verbose_name_plural': '教材学習項目一覧'},
        ),
    ]
